name: Docker
on:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@master
      with:
        dockerfile: "Dockerfile"
        config: ./.config/hadolint.yaml
    - name: Build Docker image
      run: docker build --build-arg BUILD_PLATFORM=x86_64 -t toolbox .
    - name: Run Docker image
      run: docker run -v $PWD/Dockerfile:/src/Dockerfile toolbox hadolint Dockerfile
